# Generated by Django 3.2.8 on 2022-09-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img_profile', models.ImageField(upload_to='Trainer')),
            ],
        ),
    ]
