# Generated by Django 3.2.8 on 2022-09-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='address_1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='information',
            name='address_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='information',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
