# Generated by Django 3.2.8 on 2022-09-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220905_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
