# Generated by Django 3.2.8 on 2022-09-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_information_title_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='img_about',
            field=models.ImageField(blank=True, default='', null=True, upload_to='About'),
        ),
    ]
